### ISSUE TITLE
remove the warnings in tutorials

### ISSUE THREAD

**Issue by dnabanita7** [IBM/AutoMLPipeline.jl#63]
```
┌ Warning: `eachcol(df::AbstractDataFrame, names::Bool)` is deprecated, use `if names
│     collect(pairs(eachcol(df)))
│ else
│     eachcol(df)
│ end` instead.
│   caller = top-level scope at REPL[15]:1
└ @ Core REPL[15]:1
```
I find this warning using ``eachcol()`` at the [tutorial page](https://github.com/IBM/AutoMLPipeline.jl/blob/master/docs/src/tutorial/preprocessing.md). This feature is deprecated to [eachcol(df::AbstractDataFrame, names::Bool)](https://github.com/JuliaData/DataFrames.jl/blob/d2ce9794ce9ac3ac7c7f143dad8ca91f2844936e/src/abstractdataframe/iteration.jl#L101-L145).

**Comment by ppalmes** [comment]
ok. would you like to fix it by making a PR? just edit the file containing the tutorial.

**Comment by dnabanita7** [comment]
alright!
