### ISSUE TITLE
Refactor TSML and AutoMLPipeline to have common base abstract types for faster loading.

### ISSUE THREAD

**Issue by ppalmes** [IBM/AutoMLPipeline.jl#75]
- @stevemar: my two packages are sharing the same common abstract base types but currently TSML.jl depends on AutoMLPipeline.jl to load and overload these abstract type. TSML loading is slow because of this. I would like to create a repo called AMLPBase.jl that has this abstract class which can be loaded by both AutoMLPipeline and TSML.
- @stevemar: can you please create AMLPBase.jl repo to address this issue? Thanks.

**Comment by ppalmes** [comment]
Issue: https://github.com/IBM/TSML.jl/issues/170

**Comment by stevemar** [comment]
@ppalmes you're good to go https://github.com/IBM/AMLPBase.jl

**Comment by ppalmes** [comment]
thank you! @stevemar

**Comment by ppalmes** [comment]
https://github.com/IBM/AMLPBase.jl/issues/2
