### ISSUE TITLE
Error on fresh install today

### ISSUE THREAD

**Issue by vshesh** [IBM/AutoMLPipeline.jl#87]
```julia
(@v.15) pkg> add AutoMLPipeline
   Building AutoMLPipeline → `~/.julia/packages/AutoMLPipeline/08lyk/deps/build.log`
┌ Error: Error building `AutoMLPipeline`:
│ FATAL ERROR: Symbol "ccalllib_libpython3.8.dylib40"not found
│ signal (6): Abort trap: 6
│ in expression starting at /Users/Vishesh/.julia/packages/AutoMLPipeline/08lyk/deps/build.jl:1
│ __pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
│ Allocations: 2543 (Pool: 2534; Big: 9); GC: 0
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949
```

System: 
Mac OS X: 10.13
Python version3.8 on path, through homebrew 

why does automlpipeline require python? is there a way to install it without python?

**Comment by ppalmes** [comment]
yes, it used sklearn models and preprocessing libraries. if you want pure julia implementation, you can use: https://github.com/IBM/AMLPipelineBase.jl

the base only supports randomforest, adaboost, and prunetree from DecisionTree.jl but you can extend it.

**Comment by ppalmes** [comment]
for fresh install, export this in your shell and rebuild PyCall. this is an issue in PyCall package:

export PYTHON=Conda 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.julia/conda/3/lib

**Comment by ppalmes** [comment]
I have mentioned this issue in the Readme
